# ===============================================================
# elasticsearch_install: install elasticsearch
# https://github.com/ekhoinc/ansible-examples/blob/master/elasticsearch-rolling-upgrade.yml
# ===============================================================

- include_vars: "defaults/main.yml"

  # this first step is a overkill, but here
  # in case the upgrade was cancelled by user mid playbook run
- name: make sure elasticsearch service is running
  service: name=elasticsearch enabled=yes state=started
  ignore_errors: True
  register: response
  tags: elasticsearch

- name: Wait for elasticsearch node to come back up if it was stopped
  wait_for: port={{ ansible_role_elasticsearch.transport_port }} delay=45
  when: response.changed == true
  tags: elasticsearch

  # For ansible the uri action needs httplib2
- name: ensure python-httplib2 is installed
  apt: name=python-httplib2 state=present
  tags: elasticsearch

- name: Install JRE
  apt: pkg=openjdk-{{ ansible_role_elasticsearch.openjdk_version }}-jre-headless state=latest install_recommends=no update_cache=yes
  tags: elasticsearch

- name: check current version
  uri: url=http://localhost:{{ ansible_role_elasticsearch.port }} method=GET
  register: version_found
  retries: 10
  delay: 10
  when: response.changed == true
  tags: elasticsearch

- name: Display Current elasticsearch Version
  debug: var=version_found.json.version.number
  when: response.changed == true
  tags: elasticsearch

- name: Shutdown elasticsearch node
  uri: url=http://localhost:{{ ansible_role_elasticsearch.port }}/_cluster/nodes/_local/_shutdown method=POST
  when: version_found.json.version.number != '{{ ansible_role_elasticsearch.version }}'
  tags: elasticsearch

- name: Download ElasticSearch package
  get_url:
    url: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/{{ ansible_role_elasticsearch.version }}/elasticsearch-{{ ansible_role_elasticsearch.version }}.deb
    dest: /tmp
  when: response.changed != true or version_found.json.version.number != '{{ ansible_role_elasticsearch.version }}'
  tags: elasticsearch

- name: Update elasticsearch
  command: dpkg -i /tmp/elasticsearch-{{ ansible_role_elasticsearch.version }}.deb
  notify: restart elasticsearch
  when: response.changed != true or version_found.json.version.number != '{{ ansible_role_elasticsearch.version }}'
  tags: elasticsearch

- name: clean temp file
  file: path=/tmp/elasticsearch-{{ ansible_role_elasticsearch.version }}.deb state=absent
  when: response.changed != true or version_found.json.version.number != '{{ ansible_role_elasticsearch.version }}'
  tags: elasticsearch

- name: Prevent public access
  lineinfile: >
    destfile=/etc/elasticsearch/elasticsearch.yml
    regexp="^# Prevent public access"
    line="# Prevent public access"
    insertafter="^#network.bind_host"
  tags: elasticsearch

- name: Prevent public access
  lineinfile: >
    destfile=/etc/elasticsearch/elasticsearch.yml
    regexp="network.bind_host: localhost"
    line="network.bind_host: localhost"
    insertafter="^# Prevent public access"
  tags: elasticsearch

- name: Make sure Elasticsearch starts and stops automatically with the server
  command: systemctl enable elasticsearch.service
  tags: elasticsearch
